services:
  rust-server:
    build: ./rust
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  nodejs-server:
    build: ./nodejs
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
  symfony-server:
    build: ./php-symfony
    ports:
      - "8082:8082"
