services:
  rust-server:
    build: ./rust
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
  nodejs-server:
    build: ./nodejs
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
  symfony-server:
    build: ./php-symfony
    expose:
      - "9000" # Port interne de PHP-FPM
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./php-symfony:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony-server
